version: '3.1'

services:

  php:
    image: php:latest
    volumes:
      - ./src:/var/www/html
    ports:
      - "8089:80"
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
      - ./entrypoint:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: softorium
    ports:
      - "3607:3306"
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8099:8080
    depends_on:
      - mysql
    links:
      - mysql
